# INPUT FILE(S).
[input]
    [input.oce]
        # Path to ocean data NetCDF file(s)
        path = "./data/SDC_GLO_CLIM_TS_V2_1_1900_2017_025/" 
        # Name of Salinity, Temperature and other variables in Netcdf file.
        vars = {temperature = "Temperature", salinity = "Salinity"}
        # Set to "true" if provided temperature values are "in situ". Leave it to "false" if temperature is potential temperature.
        insitu_temperature = true
        # Name of coords in Netcdf file.
        coords = {time = "time", lon = "lon", lat = "lat", depth = "depth"} 
        # Name of dimensions [time, longitude, latitude, depth] in Netcdf file.
        dims = {time = "time", lon = "lon", lat = "lat", depth = "depth"} 
        # Dimensions to be dropped out of the dataset (only if needed, otherwise leave it empty).
        drop_dims = ["observations"] # drop_dims = []
        # Decode variables directly with xarray. 
        # If set to "false", variables are decoded accessing externally the NetCDF file attributes.
        # This might be useful for issues due to xarray decoding procedure.
        decode_vars_with_xarray = true
    [input.bathy]
        # Set region depth [in meters] (set to false if not used, otherwise set the value you desire).
        set_bottomdepth = false # set_bottomdepth = 3500
        # Path to bathymetry NetCDF file
        path = "./data/bathymetry/GEBCO_2023.nc" 
        # Name of Sea Floor depth and other variables in Netcdf file.
        vars = {seafloor_depth = "elevation"}
        # Name of coords in Netcdf file.
        coords = {lon = "lon", lat = "lat"} 
        # Name of dimensions [longitude, latitude] in Netcdf file.
        dims = {lon = "lon", lat = "lat"}
# REGION DOMAIN.
[domain]
    # Domain extremants: time min, max (format compatible with numpy.datetime64)
    time = [1900-01-01T00:00:00, 2018-01-01T00:00:00]
    # Domain extremants: longitude min, max [° E]
    lon = [-30,-34]
    # Domain extremants: latitude min, max [° N]
    lat = [34.5,50.2]
    # Domain extremants: depth min, max [m]
    depth = []
# OUTPUT FILE.
[output]
    # Path to folder where output files are saved to.
    folder_path = "./output" 
    # Name of the output file (with or without '.nc' suffix).
    filename = "my_experiment"
    # Num. of modes of motion to be computed.
    n_modes = 4
    # Type of output: REGIONAL AVERAGE ("average")
    type = "average" # supported are: "average"
    # Name of output figure.
    fig_name = "my_eperiment" # = false if results should not be plotted
