[input]
    [input.oce]
        # Path to ocean data NetCDF file
        #path = "./data/mercatorglorys12v1_gl12_mean_1993_2016_01.nc" 
        path = "./data/mercatorglorys12v1_gl12_mean_1993_2016_winter.nc"
        # Name of Salinity, Temperature and other variables in Netcdf file.
        vars = {temperature = "thetao", salinity = "so"}
        # Name of coords in Netcdf file.
        coords = {time = "time", lon = "longitude", lat = "latitude", depth = "depth"} 
        # Name of dimensions [time, longitude, latitude, depth] in Netcdf file.
        dims = {time = "time", lon = "longitude", lat = "latitude", depth = "depth"} 
    [input.bathy]
        # Path to bathymetry NetCDF file
        path = "./data/bathymetry/GLO-MFC_001_030_mask_bathy.nc" 
        # Name of Sea Floor depth and other variables in Netcdf file.
        vars = {bottomdepth = "deptho"}
        # Name of coords in Netcdf file.
        coords = {lon = "longitude", lat = "latitude"} 
        # Name of dimensions [longitude, latitude] in Netcdf file.
        dims = {lon = "longitude", lat = "latitude"}
[domain]
    # Domain extremants: time min, max (in format compatible with numpy.datetime64)
    time = [1993-01-01T00:00:00, 2016-12-31T23:59:59]
    # Domain extremants: longitude min, max
    lon = [-35, -35]
    # Domain extremants: latitude min, max
    lat = [40, 40]
    # Domain extremants: depth min, max
    depth = []
[output]
    # Path where output files are saved to.
    path = "./output" 
    # Name of the output file.
    filename = "baroclinic_modes"
    # Num. of modes of motion to be computed.
    n_modes = 4
