[experiment]
    name = "baroclinic_modes" # name of the simulation
    start_datetime = 2017-04-23T00:00:00 # start date of the simulation
    end_datetime = 2017-04-23T00:00:00 # start date of the simulation
    n_modes = 4 # Num. of modes of motion to be computed
    outpath = "./data/test_case/output" # folder where output files are saved
    [experiment.domain]
        lat = [] # latitude min, max
        lon = [] # longitude min, max
[input]
    indata_path = "./data/test_case/dataset_azores/azores_Jan2021.nc" # path to data file(s)
    [input.oce]
        vars = {temperature = "thetao", salinity = "so", depth = "depth"} # Name of Salinity and Temperature variables in Netcdf files.
        dims = {time = "time", lon = "longitude", lat = "latitude", depth = "depth"} # Name of dimensions time, longitude, latitude, depth in Netcdf files.
    [input.bathy]
        inbathy_path = "./data/test_case/dataset_azores/bathymetry/mask_bathy_test_case_azores.nc" # Path to bathymetry file
        vars = {bottomdepth = "deptho"}
        dims = {lon = "longitude", lat = "latitude"}
